---
- name: Basic configuration for containers running Podman nested in LXD.
  hosts: localhost
  tasks:
    - name: Enable Unattended Reboot
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        line: 'Unattended-Upgrade::Automatic-Reboot "true";'
        insertafter: '^//Unattended-Upgrade::Automatic-Reboot '


    - name: Enable Unattended Reboot regardless of logged-in users
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        line: 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";'
        insertafter: '^//Unattended-Upgrade::Automatic-Reboot-WithUsers '

    - name: Enable Unattended Reboot regardless of logged-in users
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        line: 'Unattended-Upgrade::Automatic-Reboot-Time "03:17";'
        insertafter: '^//Unattended-Upgrade::Automatic-Reboot-Time '
    
    - name: Check Unattended Upgrade
      command: apt-config dump APT::Periodic::Unattended-Upgrade
      register: uu_check
  
    - name: Assert Unattended Upgrade is enabled
      assert:
        that:
          - "'APT::Periodic::Unattended-Upgrade \"1\";' == uu_check.stdout"

    - name: configure storage.conf
      copy:
        content: |
          [storage]
          driver = "overlay"
          runroot = "/run/containers/storage"
          graphroot = "/var/lib/containers/storage"

          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
        dest: /etc/containers/storage.conf
        backup: yes

    - name: Install packages
      apt:
        name:
          - podman
          - buildah
          - skopeo
          - slirp4netns
          - fuse-overlayfs
          - python3-pip
          - git
        update_cache: yes

    - name: Install podman-compose
      pip:
        name: https://github.com/containers/podman-compose/archive/devel.tar.gz
        executable: pip3
        state: latest
      become: yes